input          : "/Your path to/pbbams"
output    : "/your path to/output"
reference      : "/your path to/reference"


# Note: The parameter "input" and "output" are the absolute path. Do not include the "/" at the end of the paths.

