input          : "/<Your path to the directory Pensacola>/pbbams"
output    : "/<your path to the directory Pensacola>/output"
reference      : "/<your path to the directory Pensacola>/reference"


# Note: The parameter "input" and "output" are the absolute path. Do not include the "/" at the end of the paths.

