# Note1: The parameters are the absolute path. Do not include the "/" at the end of the paths.

input          : "/blue/bphl-florida/yhwinnie/pensacola/pbbams"
output    : "/blue/bphl-florida/yhwinnie/pensacola/output"
reference      : "/blue/bphl-florida/yhwinnie/pensacola/reference"
snpeffconfig : "/blue/bphl-florida/yhwinnie/pensacola/configs"

#Note2: For HiperGator users, the following two parameters do not need to be modified. For non-HiperGator users, replace the paths with your own paths to "PlusPF" and "LongQC" dirs in your computer.

db    : "/blue/bphl-florida/share/kraken_bracken_database/PlusPF"
qc    : "/apps/longqc/1.2.0c/LongQC"


